### ISSUE TITLE
Make 2.1.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticScribunto#68]
- [x] Finalize release notes
- [x] Update readme
- [x] Update "composer.json"
- [x] Update "extension.json"
- [x] Create tag
- [x] Add release to [Wikidata](https://www.wikidata.org/wiki/Special:EntityPage/Q25662078)
- [x] Update [homepage](https://www.mediawiki.org/wiki/Extension:Semantic_Scribunto)
- [x] Announce via mail
- [x] Do a release tweet on Twitter
- [x] Run `composer update` on smw.o
- [x] Update "LocalSettings.php"
- [x] Start development of new version 
  - [x] Update "composer.json" (update dev alias)
  - [x] Update "extension.json" (new alpha version)

**Comment by kghbln** [comment]
@mwjames Any objections to making this release?

**Comment by mwjames** [comment]
+1

**Comment by kghbln** [comment]
@mwjames This drives me crazy. :| The build is now failing. Not sure if a blocker?

**Comment by mwjames** [comment]
Hi,

> @mwjames This drives me crazy. :| The build is now failing. Not sure if a
> blocker?
>

I had a quick look at it and it relates to the DB version used, the CI
is running MySQL (and not MariaDB) which is more strict about using
temporary table reference within temporary tables [0].

The unit tests in SemanticScribunto rely on
`Scribunto_LuaEngineTestBase` (needed because of the Lua setup etc.)
which itself relies on `MediaWikiTestCase` and is responsible for
creating table clones as TEMPORARY TABLES by default.

So, the trick is to run the test suite with option `use-normal-tables`
to make sure that the table clones are "real" tables.

The integration tests aren't an issue because here we use SMW's
infrastructure which doesn't rely on `MediaWikiTestCase` at all.

[0] https://dev.mysql.com/doc/refman/5.7/en/temporary-table-problems.html

Cheers

**Comment by kghbln** [comment]
Thanks for the info. I was however unable to find any "use-normal-tables" option in connection with MySQL. Not sure how I could fix this.

**Comment by mwjames** [comment]
> I was however unable to find any "use-normal-tables" option in connection with MySQL. Not sure how I could fix this.

See #73.

**Comment by kghbln** [comment]
Ah ok. Couldn't have done this myself admittedly.
