### ISSUE TITLE
Make 2.2.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticScribunto#77]
- [x] Finalize release notes
- [x] Update readme
- [x] Update "composer.json"
- [x] Update "extension.json"
- [x] Create tag
- [x] Add release to [Wikidata](https://www.wikidata.org/wiki/Special:EntityPage/Q25662078)
- [x] Update [homepage](https://www.mediawiki.org/wiki/Extension:Semantic_Scribunto)
- [ ] Announce via mail
- [ ] Do a release tweet on Twitter
- [ ] Run `composer update` on smw.o
- [ ] Update "LocalSettings.php"
- [x] Start development of new version 
  - [x] Update "composer.json" (update dev alias)
  - [x] Update "extension.json" (new alpha version)

**Comment by kghbln** [comment]
@oetterer This can be done now? Drops compat with PHP 7.0 ...

**Comment by kghbln** [comment]
Apparently I lost track of what needs to be done or not or what. Please ping in case I can move forward here.

**Comment by octfx** [comment]
Will this also include support for SMW 4.0?

**Comment by kghbln** [comment]
Are there issues with SMW and the latest release of SC?

**Comment by octfx** [comment]
Composer requires SMW `~3.0` which lets the installation fail

**Comment by kghbln** [comment]
> Composer requires SMW `~3.0` which lets the installation fail. (This is also true for SRF)

Ah, I get it. Could you try with the following branch? I could do a 2.2.1 if it works.

**Comment by octfx** [comment]
So far no errors, thanks! :)

**Comment by kghbln** [comment]
Thanks for doing a field test. New version released.
